### ISSUE TITLE
Feature request: top-down navigation of inheritance hierarchy

### ISSUE THREAD

**Issue by hammar** [digitaltwinconsortium/DTDLParser#42]
Ttraversing the interface inheritance hierarchy top-to-bottom is a fairly common use case in, e.g., building GUI, so a convenience method for such navigation wouldn’t hurt. It’s not critical and it’s easy for devs using the parser to implement themselves, but it would go a little way towards better devex if it was provided out-of-the-box.

For an example of a use case and implementation, [see this app](https://github.com/RealEstateCore/DTDLOntologyViewer), specifically [starting here](https://github.com/RealEstateCore/DTDLOntologyViewer/blob/5b23debd15b5953ceb1fa4cb4742c783f10abfe4/GUI/MainWindow.xaml.cs#L224) (somewhat ugly but works).

Best,

Karl

**Comment by rido-min** [comment]
Wondering if [InterfaceInfo](https://github.com/digitaltwinconsortium/DTDLParser/blob/main/samples/DTDLParserResolveSample/InterfaceInfo.cs) (from the sample) is what you are looking for in your `DTInterfaceWrapper`

**Comment by hammar** [comment]
Very useful class! I must have missed it when I wrote that linked code. I've always implemented those convenience methods to get child telemetries, properties, etc. in extension methods, but neater to use this. Agree that this would be the obvious place to put a Children property (or whatever you prefer to name it).

**Comment by hammar** [comment]
Do you want a pull request for this, in line with the linked code?

**Comment by rido-min** [comment]
before the PR, I think will be good to have a proposal to formalize moving that class to the Parser code base..
I'm sure @jrdouceur might have some thoughts about it.

**Comment by jrdouceur** [comment]
There are two different proposals here.  One proposal -- which we have discussed internally before -- is to provide a breakout of the Contents property on DTInterfaceInfo into separate properties for each of the subtypes of Content (Property, Telemetry, etc.).  The other proposal is to provide a reverse property companion to the Extends property (perhaps ExtendedBy).  In both cases, these could be added to the DTInterfaceInfo class; however, because this class is codegenned, we would need (a) to decorate the metamodel with designations that Contents should have breakout properties and that Extends should have a reverse property and (b) to implement support for these meta-decorations in the ParserGenerator.  We would also need to write test cases for these new properties.  This is not a lot of work, perhaps 2 or 3 days of focused attention, but we really should triage these against other engineering priorities before allocating effort to them.

**Comment by jrdouceur** [comment]
Here's a sketch of what this could look like in the metamodel:

```
{
  "@id": "dtmi:dtdl:class:Interface;3",
  "@type": [ "rdfs:Class", "dtmm:Material", "dtmm:Partition", "sh:NodeShape" ],
  "sh:property": [
    {
      "@id": "dtmi:dtdl:constraint:Interface:contents;3",
      "sh:path": "dtmi:dtdl:property:contents;3",
      "sh:or": [
        { "sh:class": "dtmi:dtdl:class:Content;3" },
        { "sh:class": "dtmi:dtdl:class:Content;2" }
      ],
      . . .
      "dtmm:breakoutProperties": {
        "components": [ "dtmi:dtdl:class:Component;2", "dtmi:dtdl:class:Component;3" ],
        "properties": [ "dtmi:dtdl:class:Property;2", "dtmi:dtdl:class:Property;3" ],
        "telemetries": [ "dtmi:dtdl:class:Telemetry;2", "dtmi:dtdl:class:Telemetry;3" ],
        "commands": [ "dtmi:dtdl:class:Command;2", "dtmi:dtdl:class:Command;3" ],
        "relationships": [ "dtmi:dtdl:class:Relationship;2", "dtmi:dtdl:class:Relationship;3" ]
      },
      . . .
    },
    {
      "@id": "dtmi:dtdl:constraint:Interface:extends;3",
      "sh:path": "dtmi:dtdl:property:extends;3",
      "sh:or": [
        { "sh:class": "dtmi:dtdl:class:Interface;3" },
        { "sh:class": "dtmi:dtdl:class:Interface;2" }
      ],
      . . .
      "dtmm:reverseAs": "extendedBy",
      }
    },
    . . .
  ],
  . . .
}
```

**Comment by rido-min** [comment]
not sure if we need this in the metamodel (to enable codegen), instead of adding some handwritten code to the parser.

**Comment by jrdouceur** [comment]
The handwritten code would require DTDL-specific info, including property names and types.  This would be a drastic change to the assumptions built into the parser code structure.

**Comment by jrdouceur** [comment]
Split this into two issues: #47 and #48.
